name: digi_patient
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.2.1+18

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #  flutter_localization: ^0.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  intl:
  #  table_calendar: ^3.0.0

  #  cupertino_icons: ^1.0.2
  flutter_styled_toast: ^2.1.3
  #  device_info_plus: any
  shared_preferences: any
  #  faker: ^2.1.0
  cached_network_image: ^3.3.0

#  http: ^1.1.2
  http: ^0.13.6
  #  qr_code_scanner: ^1.0.1

  #  another_flushbar: ^1.12.29
  another_flushbar: ^1.12.30
  #  fluttertoast: ^8.2.1
  provider: ^6.0.5
  #  auto_route: ^5.0.1
  flutter_screenutil: any
  #  email_validator: ^2.1.17
  #  shared_preferences: ^2.1.0
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3
  flutterzilla_fixed_grid: ^0.0.4
  #  carousel_slider: ^4.2.1
  #  curved_navigation_bar: ^1.0.3
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.4.0
  #  rflutter_alert: ^2.0.4
  rflutter_alert: ^2.0.7
  animated_text_kit: ^4.2.2
  onboarding: ^3.1.0
  #  dropdown_button2: ^2.1.2
  #  drop_down_list: ^0.0.5
  #  pdf: ^3.8.4
  #  flutter_pdfview: ^1.3.0
  #  path_provider: ^2.0.14
  #  printing: ^5.10.3
  #  file_picker: ^5.2.7
  path_drawing: any
  #  image_painter: ^0.5.0
  modal_bottom_sheet: ^3.0.0
  photo_view: ^0.14.0

  #  agora_rtc_engine: ^6.1.0
  date_format: ^2.0.7
  human_body_selector: ^0.0.1
  zoom_widget: ^2.0.1
  badges: ^3.0.3
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  dotted_line: ^3.1.0
  lottie: ^3.0.0
  search_page: ^2.3.0
  fl_chart: ^0.67.0
  dropdown_search: ^5.0.6
  #  agora video audion and chat
  #  agora_rtm: ^1.5.8
  #  agora_chat_sdk: ^1.1.1
  #  agora_uikit: ^1.3.1
  #  agora_rtc_engine:
  #  notification
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.6.7
  firebase_core: ^2.16.0
  #  flutter_local_notifications: ^9.8.0+1
  #  dio: ^5.3.3
  #  flutter_image_compress: ^2.1.0
  url_launcher: ^6.0.9
  zego_uikit_prebuilt_call: ^4.4.2
  zego_uikit_signaling_plugin: ^2.7.6
  #  weekly_date_picker: ^1.3.2
  webview_flutter: ^3.0.4
  flutter_cached_pdfview: ^0.4.2
  pdf: ^3.1.0
  flutter_pdfview: ^1.3.2
  open_file:
  textfield_datepicker: ^0.2.0
  date_format_field: ^0.1.0
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  flutter_phone_direct_caller: ^2.1.1
  carousel_slider: ^4.2.1
  #  calendar_date_picker2: ^0.5.3
#  device_preview: ^1.1.0
  in_app_update: ^4.2.2
  google_fonts:
  bijoy_helper: ^1.0.1
  gallery_saver: ^2.1.1
  lecle_downloads_path_provider: ^0.0.2+8
#  permission_handler: ^11.0.1
  image:
  country_code_picker: ^3.0.0

  intl_phone_field: ^3.2.0
#  syncfusion_flutter_pdf: ^24.2.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  #  auto_route_generator: ^5.0.2
  #  build_runner:

  flutter_lints: ^3.0.1


flutter:
  #  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/home/
    - assets/icons/my_record/
    - assets/icons/my_medicine/
    - assets/icons/my_record/vitals/
    - assets/animation/
    - assets/fonts/kalpurush.ttf


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 200
    - family: Tiro Bangla
      fonts:
        - asset: assets/fonts/TiroBangla-Regular.ttf
          weight: 700
        - asset: assets/fonts/TiroBangla-Regular.ttf
          weight: 600
        - asset: assets/fonts/TiroBangla-Regular.ttf
          weight: 500
        - asset: assets/fonts/TiroBangla-Regular.ttf
          weight: 300
        - asset: assets/fonts/TiroBangla-Regular.ttf
          weight: 200
#    - family: kalpurush
#      fonts:
#        - asset: assets/fonts/kalpurush.ttf
#          weight: 700
#        - asset: assets/fonts/kalpurush.ttf
#          weight: 600
#        - asset: assets/fonts/kalpurush.ttf
#          weight: 500
#        - asset: assets/fonts/kalpurush.ttf
#          weight: 300
#        - asset: assets/fonts/kalpurush.ttf
#          weight: 200

